package io.github.shogowada.scala.jsonrpc.example.e2e.websocket

import scala.concurrent.{Future, Promise}

class ClientApiImpl(promisedId: Promise[String]) extends ClientApi {
  def id: Future[String] = {
    // Client ID needs to be promised because it is generated by server.
    promisedId.future
  }
}

class RandomNumberObserverApiImpl extends RandomNumberObserverApi {
  override def notify(randomNumber: Int): Unit = {
    // Every time we receive random number from server, we just log it.
    println(randomNumber)
  }
}
